name: beer_hero
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: '^0.5.11'
  cloud_firestore: '^0.7.3'
  cupertino_icons: '^0.1.0'
  url_launcher: '^3.0.3'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/beer-mug.png